#+title: osu!info by Jerops
#+author: Андрей Куленко

** Мой первый опыт в создании веб-сайтов.

При создании сайта использовалась вёрстка при помощи HTML/CSS, а также
базовое программирование на JavaScript. Мини-курс по основам создания
сайтов и самостоятельное обучение хорошо помогли мне постичь основы
веб-разработки.

osu!info был создан в рамках образовательного проекта "К.О.Д."

** Содержание сайта

В качестве темы сайта я выбрал свою любимую ритм-игру - osu!
Достаточно углубленные знания игры позволили мне развёрнуто написать
о её основах, особенностях, фишках и непосредственном опыте игры.

** Учитываемые критерии

Разработка велась с учётом критерий, указанных в Положении о проведении
конкурсного отбора:

- Сайт состоит из одной страницы.
- Нормированное табулирование в коде HTML/CSS/JS.
- Использование меню навигации по странице.
- Использование псевдоклассов CSS.
- Подключение шрифтов из библиотек Google Fonts.
- Соблюдение отступов на странице.
- Использование JavaScript.
- Хорошее качество выбранных изображений на странице.
  (Специально для сайта был нарисован логотип и вставлены внешние
  изображения в формате svg. Для разнообразия были использованы
  видеофрагменты)
- Приемлемое качество оформления страницы.

** Критерий, которого придержаться не удалось

Разработка сайта отняла больше времени чем предполагалось, поэтому
работа сдаётся не вовремя. Но к счастью для меня, всё это время было
проведено с пользой в изучении дополнительной информации о вёрстке и
разработке сайтов.

** Дополнительные возможности сайта

Приведённых в Положении критериев было недостаточно, чтобы
удовлетворить качеству сайта, поэтому для достижения таковой цели
использовались следующие особенности:

- Использование свойства flex и его свойств.
- Базовое применение адаптивного дизайна с помощью Media Queries.

** Благодарность

Как участник проекта, хочу поблагодарить организаторов и
преподавателей за активность и желание обучать людей в востребованной
сфере.
